name: test
on:
 push:
  branches: [develop]
jobs:
 GitHubActions:
  runs-on: windows-latest
  steps:
   - name: flowers
     run: echo "i like red rose"
   - name: fruits
     run: echo "apple is in red colour"
   - name: person
     run: echo" my name is swarupa Rani"
   
   
       
          
   
  
 
